project('udev-hid-bpf', 'rust', 'c',
        version: '2.2.0-20251121', # Update Cargo.toml too!
        default_options : [ 'c_std=gnu99', 'warning_level=2' ],
        meson_version: '>= 1.0.0')

prefix = get_option('prefix')
bindir = prefix / get_option('bindir')
bpfdir = prefix / 'lib' / 'firmware' / 'hid' / 'bpf'
man1dir  = prefix / get_option('mandir') / 'man1'

lookup_bpfdirs = []
dirs = get_option('bpfdirs')
if dirs.length() == 0
    dirs = ['PREFIXED_BPFDIR']
endif
foreach d: dirs
    d = d.replace('PREFIXED_BPFDIR', bpfdir)
    if not lookup_bpfdirs.contains(d)
        lookup_bpfdirs += [d]
    endif
endforeach

pkgconfig = import('pkgconfig')
udevdir = get_option('udevdir')
if udevdir == ''
    udev = dependency('udev', required: false)
    if udev.found()
        udevdir = udev.get_variable('udevdir')
    else
        udevdir = prefix / 'lib' / 'udev'
    endif
endif

# Required by Cargo via libudev-sys
libudev = dependency('libudev')

bpf_compiler = get_option('bpf-compiler')
cc = meson.get_compiler('c')
cc_id = cc.get_id()
if cc_id == bpf_compiler
    foreach func: ['memcpy', 'memcmp']
        if not cc.compiles(f'''
            int main(void) {
                __builtin_@func@(0, 0, 0);
                return 0;
            }
            '''
        )
            cc_version = cc.version()
            error(f'@cc_id@ @cc_version@ does not support __builtin_@func@(), try a newer version')
        endif
    endforeach
else
    warning(f'C compiler is @cc_id@ but BPF compiler is @bpf_compiler@')
endif

cflags = [
	'-Wno-unused-parameter',
	'-Wno-missing-field-initializers',
	'-Wno-missing-declarations',

	'-Wundef',
	'-Wlogical-op',
	'-Wpointer-arith',
	'-Wuninitialized',
	'-Winit-self',
	'-Wimplicit-fallthrough',
	'-Wredundant-decls',
	'-Wincompatible-pointer-types',
	'-Wformat=2',
]
add_project_arguments(cc.get_supported_arguments(cflags), language : 'c')

use_bpf_tracing = get_option('bpf-tracing')

subdir('src')

cargo = find_program('cargo', required: true)
cargo_options = [
    '--manifest-path', meson.project_source_root() / 'Cargo.toml',
    '--target-dir', meson.project_build_root(),
]

if get_option('buildtype') in ['debug', 'debugoptimized']
  cargo_options += [ '--all-targets' ]
  rust_target = 'debug'
  message('Building in debug mode')
else
  cargo_options += [ '--release' ]
  rust_target = 'release'
  message('Building in release mode')
endif

# Now the cargo invocation
cargo_env = {
    'MESON_BUILD': '1',
    'MESON_BINDIR': bindir,
    'CARGO_HOME': meson.project_build_root() / 'cargo-home',
    'BPF_SOURCE_ROOT': meson.project_source_root(),
    'BPF_LOOKUP_DIRS': lookup_bpfdirs,
}

cargo_files = files(
    'Cargo.toml',
    'build.rs',
    'src/bpf/attach.bpf.c',
    'src/bpf.rs',
    'src/btf_validation.rs',
    'src/hid_bpf_wrapper.h',
    'src/hidudev.rs',
    'src/lib.rs',
    'src/main.rs',
    'src/meson.build',
    'src/modalias.rs',
    'src/bin/hid-rdesc-to-c-struct.rs',
)

# Note: with the env set up the cp command only copies the
# udev-hid-bpf binary, the bpf files are built in-place (i.e. builddir/bpf)
# because of the crazy build.rs script we need.
cargo_build = custom_target(
  'cargo-build',
  build_by_default: true,
  output: meson.project_name(),
  console: true,
  install: true,
  install_dir: bindir,
  depend_files: cargo_files,
  env: cargo_env,
  command: [
    cargo, 'build',
    cargo_options,
    '&&',
    'cp', rust_target / meson.project_name(), '@OUTPUT@',
  ]
)

# Build hid-rdesc-to-c-struct tool (for test development only, not installed)
hid_rdesc_tool = custom_target(
  'hid-rdesc-to-c-struct',
  build_by_default: false,
  build_always_stale: true,
  output: 'hid-rdesc-to-c-struct',
  console: true,
  install: false,
  depends: cargo_build,
  command: [
    'cp', rust_target / 'hid-rdesc-to-c-struct', '@OUTPUT@',
  ]
)

test('cargo test',
    cargo,
    args: ['test'],
    env: cargo_env,
    timeout: 120,
)

meson.add_devenv(cargo_env)

udev_config = configuration_data()
# See make_release.sh - if set we leave a placeholder
# that we can use in install.sh
if get_option('placeholder-udev-rules-file')
    udev_config.set('BINDIR', '@@BINDIR@@')
else
    udev_config.set('BINDIR', bindir)
endif
configure_file(input: '81-hid-bpf.rules.in',
               output: '@BASENAME@',
               configuration: udev_config,
               install: true,
               install_dir: udevdir / 'rules.d')

generate_hwdb_py = find_program('tools/generate-hwdb.py')
builds = [
    { 'enabled': install_testing, 'suffix': 'testing', 'files': bpf_o_files_testing },
    { 'enabled': install_stable, 'suffix': 'stable', 'files': bpf_o_files_stable },
]

foreach build: builds
    if build['enabled']
        json_data = custom_target(
            'extract json data @0@'.format(build['suffix']),
            depends: cargo_build,
            output: 'bpf-@0@.json'.format(build['suffix']),
            capture: true,
            command: [
                cargo_build,
                'inspect',
                build['files'],
            ]
        )

        # T, S, or U
        suffix = build['suffix'].substring(0, 1).to_upper()
        prop_prefix = 'HID_BPF_@0@_'.format(suffix)

        custom_target(
            'hwdb files @0@'.format(build['suffix']),
            depends: json_data,
            build_by_default: true,
            output: '81-hid-bpf-@0@.hwdb'.format(build['suffix']),
            input: json_data,
            command: [
                generate_hwdb_py,
                '--prefix', prop_prefix,
            ],
            feed: true,
            capture: true,
            install: true,
            install_dir: udevdir / 'hwdb.d',
        )
    endif
endforeach

man_config = configuration_data()
man_config.set('VERSION', meson.project_version())
man_config.set('BPF_LOOKUP_DIRS', ', '.join(lookup_bpfdirs))
man_config.set('PREFIX', prefix)
configure_file(input: 'udev-hid-bpf.man',
               output : '@BASENAME@.1',
               configuration : man_config,
               install_dir : man1dir)

kernel_version = 'unknown'
uname = find_program('uname', required: false)
if uname.found()
    uname_result = run_command(uname, '-r', check: false, capture: true)
    if uname_result.returncode() == 0
        kernel_version = uname_result.stdout().strip()
        if kernel_version.version_compare('< 6.3')
            warning('kernel version is @0@ but we require 6.3 or later.'.format(kernel_version))
        endif
    endif
endif

subdir('test')

summary({'kernel version': kernel_version}, section: 'Host machine')
summary({'udevdir': udevdir,
         'prefix': prefix,
         'bindir': bindir,
         'bpfdir': bpfdir,
         'bpf lookup dirs': lookup_bpfdirs,
         }, section: 'Directories')
